### ISSUE TITLE
babelHelpers set to inline?

### ISSUE THREAD

**Issue by cgatian** [kraftdorian/react-ts-rollup-starter-lib#1]
Curious to know why you [set babelHelpers](https://github.com/kraftdorian/react-ts-rollup-starter-lib/blob/master/rollup.config.js#L25) `inline`?

The docs recommend `runtime` and explicitly say not to use `inline`.
https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers

**Comment by kraftdorian** [comment]
Hi, thank you so much for finding that!
I think I just set the default value of that prop explicitly when testing the behavior, and it stayed.

It definitely needs to be changed, I'll give it a try.

**Comment by cgatian** [comment]
So I've been messing around as well, which is how I came across your post.

This Stackblitz could help to rapidly test different setups:
https://stackblitz.com/edit/node-r78guv?file=src/index.js

**Comment by cgatian** [comment]
I think the setup there is actually what you want. Still researching though, there are a lot of properties and sometimes the description is difficult to understand.

**Comment by kraftdorian** [comment]
thank you once again for creating the issue and linking the example, for now, I went with the default config there after looking at https://babeljs.io/docs/en/babel-plugin-transform-runtime.

tested with a few builds and seems like it's working fine.

**Comment by cgatian** [comment]
Great. I think the setup you have is correct.

I still am having an issue with the additional babel runtime as a dependency of the package. Maybe a lot library authors are doing it and I never see or noticed it, just something isn't making sense...
