### ISSUE TITLE
Why babel for typescript compilation?

### ISSUE THREAD

**Issue by cgatian** [kraftdorian/react-ts-rollup-starter-lib#3]
I'm wondering if there's a reason to even use babel? Couldn't you just use this ts plugin?

https://github.com/ezolenko/rollup-plugin-typescript2

**Comment by cgatian** [comment]
I'm going to look at some popular repos to see if I can figure figure this out.

**Comment by kraftdorian** [comment]
When I started to write the [related article](https://dev.to/kraftdorian/creating-react-typescript-component-library-basic-rollup-js-setup-3k93), this topic was new to me, so I used some external tutorials, and babel is used there.

I think pure TypeScript is a good fit here.
I'll be able to update the article then.

Thanks!

**Comment by cgatian** [comment]
I think when you use the babel/preset-typescript, typescript type checking is ignored and only transpilation occurs. This could lead to invalid types shipped to consumers

**Comment by kraftdorian** [comment]
I think we're good with the current solution anyway, because the build script actually uses the TypeScript compiler for type-checking, so potential errors will be caught before the rollup build process.

I tested when I didn't actually have the babel installed, still, typescript was able to catch the typing issue.

```json
{
  "build": "rimraf dist && tsc --emitDeclarationOnly && rollup --config",
}
```

**Comment by cgatian** [comment]
Oh you might be running it twice then. The roll-up plugin already does it

**Comment by kraftdorian** [comment]
Yes, that was an issue. Thanks for spotting this. I believe now it's fine 😄
